[package]
name = "abr2png"
version = "0.1.0"
authors = ["scurest <scurest@users.noreply.github.com>"]
license = "GPL-3.0"
readme = "README.md"
description = "Extract image brushes from Adobe ABR files as PNGs."

[dependencies]
byteorder = "0.4.2"
image = "0.6.1"
getopts = "0.2.14"
